name: shopping_list_repository
description: Dart package which manages the firestore domain.
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cloud_firestore: ^1.0.5
  equatable: ^2.0.0
  firebase_core: ^1.0.3
  flutter:
    sdk: flutter
  json_annotation: ^4.0.1
  rxdart: ^0.26.0

dev_dependencies:
  build_runner: ^2.0.1
  flutter_test:
    sdk: flutter
  json_serializable: ^4.1.1
  mockito: ^5.0.4
