name: shopping_list
description: A cross platform shopping list app with Firebase.
publish_to: "none"
version: 1.1.0+13

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cloud_firestore: ^2.2.0
  equatable: ^2.0.3
  firebase_auth: ^3.0.1
  firebase_core: ^1.2.0
  flex_color_picker: ^2.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_signin_button: ^2.0.0
  google_sign_in: ^5.0.1
  json_serializable: ^6.1.6
  logging: ^1.0.1
  meta: ^1.1.8
  money2: ^2.0.2
  provider: ^6.0.2
  shared_preferences: ^2.0.5
  universal_html: ^2.0.8
  universal_platform: ^1.0.0-nullsafety

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.0.2
  flutter_launcher_icons: ^0.9.0
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  mockito: ^5.0.3

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/
