name: shopping_list
description: A cross platform shopping list app with Firebase.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  authentication_repository:
    path: packages/authentication_repository
  settings_ui:
    git:
      url: git@github.com:Merrit/flutter-settings-ui.git
      ref: 31121cbd7c28567ecff5b864c7a23840375727b6
  bloc: ^7.0.0
  cloud_firestore: ^1.0.3
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0-nullsafety.1
  equatable: ^2.0.0
  firebase_auth: ^1.0.1
  firebase_core: ^1.0.2
  flutter_bloc: ^7.0.0
  grouped_list: ^4.0.0
  json_annotation: ^4.0.1
  logging: ^1.0.1
  money2: ^2.0.2
  pedantic: ^1.11.0
  provider: ^5.0.0
  shared_preferences: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0
  build_runner: ^1.11.0
  json_serializable: ^4.1.0
  mockito: ^5.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/
