name: shopping_list
description: A cross platform shopping list app with Firebase.
publish_to: "none"
version: 1.11.0+24

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cloud_firestore: ^4.4.2
  collection: ^1.16.0
  equatable: ^2.0.3
  firebase_auth: ^4.2.8
  firebase_core: ^2.6.1
  flex_color_picker: ^3.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_signin_button: ^2.0.0
  font_awesome_flutter: ^9.2.0
  freezed_annotation: ^2.2.0
  google_sign_in: ^5.0.1
  helpers:
    git:
      url: https://github.com/Merrit/helpers.git
      ref: 2dd7305c83b9b2a86829c46a4cb7fb1d5857ff4f
  json_annotation: ^4.8.0
  logger: ^1.1.0
  meta: ^1.1.8
  money2: ^3.1.3
  path_provider: ^2.0.12
  provider: ^6.0.2
  shared_preferences: ^2.0.5
  universal_html: ^2.0.8
  universal_platform: ^1.0.0-nullsafety

dev_dependencies:
  bloc_test: ^9.1.1
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  mockito: ^5.0.3
  mocktail: ^0.3.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/
