name: shopping_list
description: A cross platform shopping list app with Firebase.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  settings_ui:
    git:
      url: git@github.com:Merrit/flutter-settings-ui.git
      ref: 31121cbd7c28567ecff5b864c7a23840375727b6
  cloud_firestore: ^1.0.3
  cupertino_icons: ^1.0.2
  firebase_auth: ^1.0.1
  firebase_core: ^1.0.2
  grouped_list: ^4.0.0
  json_annotation: ^4.0.1
  logging: ^1.0.1
  money2: ^2.0.2
  provider: ^5.0.0
  shared_preferences: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.0
  json_serializable: ^4.1.0
  mockito: ^5.0.3
  pedantic: ^1.11.0

flutter:
  uses-material-design: true
