name: shopping_list
description: A cross platform shopping list app with Firebase.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  authentication_repository:
    path: packages/authentication_repository
  shopping_list_repository:
    path: packages/shopping_list_repository
  equatable: ^2.0.0
  flutter_bloc: ^7.0.0
  flutter_signin_button: ^2.0.0
  grouped_list: ^4.0.0
  logging: ^1.0.1
  money2: ^2.0.2
  pedantic: ^1.11.0
  provider: ^5.0.0
  shared_preferences: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0
  mockito: ^5.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/
