name: Build Android apk & bundle

on:
  # Enable manual run
  workflow_dispatch:
  # Verify builds succeed on pull requests
  pull_request:
  # Build & deploy for tag events matching v*, i.e. v1.0.0, v20.15.10
  push:
    tags:
      - "v*"

jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - run: echo $SIGNING_KEY | base64 -d > android/app/key.jks
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      - uses: subosito/flutter-action@v2.3.0
        with:
          channel: beta
      - run: |
          flutter pub get
          flutter pub run build_runner build
          flutter test
          flutter build apk
          flutter build appbundle
        env:
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          ALIAS: ${{ secrets.ALIAS }}
          KEY_PATH: key.jks
      - uses: actions/upload-artifact@v2
        with:
          name: app-release.aab
          path: build/app/outputs/bundle/release/
      - uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/
