name: Run tests
on: [pull_request, release, workflow_dispatch]
jobs:
  flutter_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.5.0
        with:
          channel: beta
      - run: |
          flutter pub get
          flutter pub run build_runner build
          flutter test
